[project]
name = "flakes-e"
version = "0.1.0"
description = "a django web app for searching movies with tmdb"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "uvicorn>=0.35.0",
]

[dependency-groups]
dev = [
    "djlint>=1.36.4",
]
